apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomix-smr-host2-deployment
spec:
  template:
    metadata:
      name: atomix-smr-host2-pod
      labels:
        type: atomix-smr-host
        name: atomix-smr-host2-pod
    spec:
      containers:
        - name: atomix-smr
          image: lucasbfernandes/atomix-smr
          envFrom:
            - configMapRef:
                name: atomix-smr-host2-config
  replicas: 1
  selector:
    matchLabels:
      name: atomix-smr-host2-pod