apiVersion: v1
kind: Deployment
metadata:
  name: atomix-smr-host1-deployment
spec:
  template:
    metadata:
      name: atomix-smr-host1-pod
    spec:
      containers:
        - name: atomix-smr
          image: lucasbfernandes/atomix-smr
      envFrom:
        - configMapRef:
            name: atomix-smr-host1-config
  replicas: 1