name: atomix-smr-release

on:
  push:
    branches: [ release-* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build
      run: docker build -t lucasbfernandes/atomix-smr:latest -f ./Dockerfile .

    - name: Login
      run: docker login -u "lucasbfernandes" -p "99103457"

    - name: Tag versions
      run: docker tag lucasbfernandes/atomix-smr:latest lucasbfernandes/atomix-smr:${{ steps.get_version.outputs.VERSION }}

    - name: Push Version
      run: docker push lucasbfernandes/atomix-smr:${{ steps.get_version.outputs.VERSION }}

    - name: Push Latest
      run: docker push lucasbfernandes/atomix-smr:latest
